### ISSUE TITLE
CDK deployment fails

### ISSUE THREAD

**Issue by Kevlw-AWS** [aws-samples/amazon-q-business-code-analysis#16]
I tried deploying the CDK stack with the suggested command
`npx cdk deploy --parameters RepositoryUrl=https://github.com/aws-samples/langchain-agents.git --parameters ProjectName=Langchain-Agents --require-approval never`

I received this error
```
❌  QBusinessCodeAnalysisCdkStack failed: Error: The following CloudFormation Parameters are missing a value: IdcArn
    at new ParameterValues (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:445:11806)
    at _TemplateParameters.updateExisting (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:445:11063)
    at deployStack (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:449:4888)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:454:199515)
    at async /Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:454:181237

 ❌ Deployment failed: Error: The following CloudFormation Parameters are missing a value: IdcArn
    at new ParameterValues (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:445:11806)
    at _TemplateParameters.updateExisting (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:445:11063)
    at deployStack (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:449:4888)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:454:199515)
    at async /Users/kevlw/Documents/Testbench/amazon-q-business-code-analysis/cdk/node_modules/aws-cdk/lib/index.js:454:181237

The following CloudFormation Parameters are missing a value: IdcArn
```

**Comment by KBB99** [comment]
Hi @Kevlw-AWS . You need to add IdC as one of the parameters:

npx cdk deploy --parameters RepositoryUrl=<repository_git_url> --parameters ProjectName=<project_name> --parameters IdcArn=<identity_center_arn> --require-approval never
